### PR TITLE
Timeout Stream Read

### PR DESCRIPTION
**Pull request by aarshkshah1992**
@vyzo @Stebalien 

I read through the circuit stream handling code and looks like this is the ONLY change we need to make.
Is there anything/any other incoming stream read we need to time out here ?

### CODE REVIEW

**Review by vyzo — APPROVED** [review]
LGTM, I don't think we need timeouts anywhere else.

**Comment by vyzo** [comment]
what's with the test failures?

**Comment by vyzo** [comment]
```
ERROR: some files not gofmt'ed:

./relay.go
```

you need to gofmt; can you set your editor to do it automatically?

**Review by Stebalien — APPROVED** [review]

**Comment by aarshkshah1992** [comment]
@vyzo My new setup didn't have go fmt configured. Have fixed it.

**Pull request merged**
